'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SIFACToEDC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Montant disponible {0}.
        '''</summary>
        Public ReadOnly Property AvailableBudget() As String
            Get
                Return ResourceManager.GetString("AvailableBudget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à =&apos;{0}&apos;!{1}.
        '''</summary>
        Public ReadOnly Property CellRef() As String
            Get
                Return ResourceManager.GetString("CellRef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à ={0}.
        '''</summary>
        Public ReadOnly Property CellRef2() As String
            Get
                Return ResourceManager.GetString("CellRef2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Dépenses jusqu&apos;en {0}.
        '''</summary>
        Public ReadOnly Property DepenseUntil() As String
            Get
                Return ResourceManager.GetString("DepenseUntil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à =&apos;{0}&apos;!{1}+&apos;{0}&apos;!{2}.
        '''</summary>
        Public ReadOnly Property DirectCellSum() As String
            Get
                Return ResourceManager.GetString("DirectCellSum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à ={0}+SUM({1}:{2}).
        '''</summary>
        Public ReadOnly Property DirectCellSum2() As String
            Get
                Return ResourceManager.GetString("DirectCellSum2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à ={0}+{1}.
        '''</summary>
        Public ReadOnly Property DirectCellSum3() As String
            Get
                Return ResourceManager.GetString("DirectCellSum3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à ={0}-{1}.
        '''</summary>
        Public ReadOnly Property DirectDiff() As String
            Get
                Return ResourceManager.GetString("DirectDiff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à ={0}-{1}-SUM({2}:{3}).
        '''</summary>
        Public ReadOnly Property DirectDiff2() As String
            Get
                Return ResourceManager.GetString("DirectDiff2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Montant engagé + liquidé {0}.
        '''</summary>
        Public ReadOnly Property EngagedBudget() As String
            Get
                Return ResourceManager.GetString("EngagedBudget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &gt; {0}.
        '''</summary>
        Public ReadOnly Property HeaderOverYear() As String
            Get
                Return ResourceManager.GetString("HeaderOverYear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Budget initial {0}.
        '''</summary>
        Public ReadOnly Property InitialBudget() As String
            Get
                Return ResourceManager.GetString("InitialBudget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ligne venant de {0}.
        '''</summary>
        Public ReadOnly Property LineFrom() As String
            Get
                Return ResourceManager.GetString("LineFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Budget modifié {0}.
        '''</summary>
        Public ReadOnly Property ModifiedBudget() As String
            Get
                Return ResourceManager.GetString("ModifiedBudget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à {0}. Il a des lignes avec commentaires qui ne sont plus utilisées..
        '''</summary>
        Public ReadOnly Property Problem1() As String
            Get
                Return ResourceManager.GetString("Problem1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à {0}. Il y a des commentaires en dehors des tables..
        '''</summary>
        Public ReadOnly Property Problem2() As String
            Get
                Return ResourceManager.GetString("Problem2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à {0}. Il y a des commentaires sur les lignes de somme..
        '''</summary>
        Public ReadOnly Property Problem3() As String
            Get
                Return ResourceManager.GetString("Problem3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à {0}. Il y a des commentaires sous les tables..
        '''</summary>
        Public ReadOnly Property Problem4() As String
            Get
                Return ResourceManager.GetString("Problem4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Travail en cours.
        '''</summary>
        Public ReadOnly Property ProgressTitle() As String
            Get
                Return ResourceManager.GetString("ProgressTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à =SUM({0}:{1}).
        '''</summary>
        Public ReadOnly Property SumRange() As String
            Get
                Return ResourceManager.GetString("SumRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Liste des problèmes de commentaires pour l&apos;année {0}.
        '''</summary>
        Public ReadOnly Property YearProblem() As String
            Get
                Return ResourceManager.GetString("YearProblem", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
